INSERT INTO dbo.Category (ParentId, Category) VALUES 
(NULL, 'Drive Train'),
(1,    'Wheels'),
(1,    'Trucks'),
(1,    'Mount'),
(1,    'Pulleys'),
(NULL, 'Accessory'),
(6,    'Lights'),
(6,    'X-Thing'),
(6,    'Pulley Cover'),
(6,    'Hardware'),
(NULL, 'Chassis'),
(11,   'Deck'),
(11,   'Enclosure'),
(NULL, 'Electric'),
(14,   'Motor'),
(14,   'ESC'),
(14,   'Remote'),
(14,   'Battery'),
(14,   'BMS'),
(14,   'Charger');